### ISSUE TITLE
Error makes LC Automator stuck

### ISSUE THREAD

**Issue by ilyakatz** [jgillick/LendingClubAutoInvestor#31]
Sometimes, I get this error
```
INFO: 2015-07-22 10:42 - Checking for funds to invest...
ERROR: 2015-07-22 10:42 - Expecting property name enclosed in double quotes: line 1 column 39 (char 38)
```

And after this error the process just hangs quietly, not doing anything and not dying

**Comment by jgillick** [comment]
Sorry for not looking at this sooner. Are you still getting this at times? Run the tool with the `-v` flag for more verbose output and add that to the ticket. Thanks.

**Comment by ilyakatz** [comment]
thanks @jgillick, i haven't had this problem in a while so can close it.
